### ISSUE TITLE
python 3 support

### ISSUE THREAD

**Issue by kapilt** [capitalone/cloud-custodian#705]
---------------

### Work plan

- [x] add future imports: #1214
- [x] set up CI to run against Python 3.6, block merge on regressions: #1234 
- [x] update dev docs: #1303
- [x] fix one thing at a time (consider [modernize](http://python-modernize.readthedocs.io/en/latest/)):
  - [x] ~~cStringIO &rarr; io: #1272~~ let's go with ...
  - [x] unlock test files: #1285
  - [x] basestring -> six.string_types: #1286
  - [x] mondo PR: #1376
- [x] block merge on new test failures under Python 3: #1388
- [x] fix remaining tests:
  - [x] mu/lambda-related: #1400
  - [x] one-offs: #1389
  - [x] csv-related & remaining one-offs: #1396
- [x] ~~constrain runtime from local to lambda:~~ #1546
- [x] allow for changing runtimes: #1638
- [x] allow for namespace packages in `PythonPackageArchive`: #1677
- [x] port tools to start getting a feel for real use
  - [x] ~~index~~
  - [x] ~~logexporter~~
  - [x] mailer: #1417
  - [x] ~~org~~
  - [x] ~~salactus~~
  - [x] sentry: #1420
  - [x] ~~sphere11~~
  - [x] ~~sphinxext~~
  - [x] ~~traildb~~
- [x] update docs w/ beta status for py36: #1519
- [x] ~~start running live~~
- [x] ~~fix bugs~~

**Comment by alfredgamulo** [comment]
Lambda now supports 3.6: https://aws.amazon.com/about-aws/whats-new/2017/04/aws-lambda-supports-python-3-6/

**Comment by whit537** [comment]
Good first step is to add future imports. Looking at that ...

**Comment by whit537** [comment]
I guess there was a PyCon keynote about porting at Instagram. Will keep an eye out for video.

**Comment by whit537** [comment]
https://www.youtube.com/watch?v=66XoCk79kjM#t=12m25s

**Comment by scotwk** [comment]
@whit537 - not sure if it's helpful or too generic, but thought of your work when I was listening to it

**Comment by whit537** [comment]
Quite helpful, @scotwk. Thank you. I like the [idea](https://www.youtube.com/watch?v=66XoCk79kjM#t=24m35s) of using [`modernize`](http://python-modernize.readthedocs.io/en/latest/) to fix one class of issues at a time, gradually ratcheting down CI. I've updated the ticket description with a work plan.

**Comment by whit537** [comment]
PR for initial CI wiring in #1234.

**Comment by whit537** [comment]
Alright, got our first actual upgrade in #1272.

**Comment by whit537** [comment]
Second in #1277.

**Comment by whit537** [comment]
Mondo PR in https://github.com/capitalone/cloud-custodian/pull/1376 to fix most failures. From there I have a few more minor fixes ready to go, am thinking it's about time to flip from whitelist to blacklist. I.e., `ratchet.py` fails if new py36 failures introduced (vs. py36 regressions only). Remaining fixes fall under three headings:

- mu/lambda related
- csv related ([bit](https://stackoverflow.com/questions/37866883/unable-to-write-byte-like-string-using-csv-writer-in-python3) [of a](https://stackoverflow.com/questions/38770522/python-3-csv-writer-prints-bytes-with-prefix-and-quotes) [mess](https://stackoverflow.com/questions/5180555/python-2-and-3-csv-reader))
- a dozen or two misc small cleanups

**Comment by whit537** [comment]
Once #1396 and #1400 are in, the last major core piece on my radar is to update lambda deployment to allow for varying the runtime between py27 and py36. At that point we'll be ready to start beta-testing.

First tier could/should be the tools. We've got manual test scripts for the mailer and sentry in their READMEs. I guess we develop protocols if not automated tests for the other five as well. @skurfer Sound like a good next step for you here?

Beyond that, anyone wanna be an early adopter on this and help us test? @alfredgamulo? @JohnTheodore? :)

**Comment by skurfer** [comment]
I’ve tracked down the intermittent failure in `test_cli.py` @whit537. The Python 2 tests Pickle some data in `~/.cache/cloud-custodian.cache`. When the tests run under Python 3, it loads that file and hits a `UnicodeDecodeError`.

There are options for `pickle.load()` that will fix this, but they’re only available under Python 3. I don’t think writing the file using Python 2 and reading it with Python 3 represents a real use-case that we need to worry about, so I’m not going to make any changes to the code, but maybe that cache should be wiped when tests are done.

As for the tools, I’ve only done light work on the mailer so I’m not too familiar, but if that’s what’s next, I’d be happy to start on them.

**Comment by whit537** [comment]
Nice find!

**Comment by whit537** [comment]
Sentry and mailer are ready in #1417 and #1420.

**Comment by kapilt** [comment]
re the test_cli.py and cache .. those tests should definitely be using temp files explicitly for the cache.

**Comment by whit537** [comment]
Beta status noted in #1519.

> I guess we develop protocols if not automated tests for the other five as well.

Planning to go here ^^^ next.

**Comment by whit537** [comment]
Per call with @ocampocj the plan now is to land the PRs currently open (#1396 #1546 #1417 #1420) plus one more with minimal changes to `tools/` and call it a day here. Having Python 3 support in beta is good enough for now, we can push further in response to customer demand.

**Comment by whit537** [comment]
#1396 and ~~#1546~~ &rarr; #1638 are in. #1417 and #1420 are still hanging out there but should be real close. May or may not see an org tool update. Home stretch!

**Comment by whit537** [comment]
Sentry (#1420) is in.

Mailer (#1417) and a pre-req (#1710) are the last two PRs.

**Comment by whit537** [comment]
#1710 is in! Last one is #1417! 😮

**Comment by whit537** [comment]
#1710 is in! We are ported to Python 3! Closing!

**Comment by ccyr-hbs** [comment]
Is there a way to Upgrade from python3.7 to 3.11?

Looks like the mailer is running python3.7. This versions is EOL.

AWS Message:
"We are ending support for Python 3.7 in AWS Lambda. This follows Python 3.7 End-Of-Life (EOL) reached on June 27, 2023 [1]."

Will this be done under the hood when installing the mailer, or is there a way to force an update?
